### ISSUE TITLE
erorr

### ISSUE THREAD

**Issue by ghost** [Rdimo/Hazard-Token-Grabber-V2#376]
injector not working

**Comment by Rdimo** [comment]
shi mb mb let me read your mind and try to figure out why and how

**Comment by Wapperr** [comment]
> shi mb mb let me read your mind and try to figure out why and how

it does not give any errors, when I restart discord, I log out of the account, login and log out, and the message does not come

**Comment by Rdimo** [comment]
> > shi mb mb let me read your mind and try to figure out why and how
> 
> it does not give any errors, when I restart discord, I log out of the account, login and log out, and the message does not come

alr thats better, let me look into it

**Comment by Wapperr** [comment]
Waiting

> > > shi mb mb let me read your mind and try to figure out why and how
> > 
> > 
> > it does not give any errors, when I restart discord, I log out of the account, login and log out, and the message does not come
> 
> alr thats better, let me look into it

**Comment by Wapperr** [comment]
> > > shi mb mb let me read your mind and try to figure out why and how
> > 
> > 
> > it does not give any errors, when I restart discord, I log out of the account, login and log out, and the message does not come
> 
> alr thats better, let me look into it

I'm Waiting

**Comment by Wapperr** [comment]
> > > shi mb mb let me read your mind and try to figure out why and how
> > 
> > 
> > it does not give any errors, when I restart discord, I log out of the account, login and log out, and the message does not come
> 
> alr thats better, let me look into it

QWE

**Comment by karimawii** [comment]
@Rdimo I cloned the latest files, tried the exe on my end it operated normally sending data to the webhook, but the injection doesn't work at all, I logged out my account, QR login is available (which I believe the injection disables) and when I type my pass + 2fa code and login, there's no embed sent by a webhook with the password and other account data like it used to do before.

**Comment by Rdimo** [comment]
> @Rdimo I cloned the latest files, tried the exe on my end, it operated normally sending data to the webhook, but the injection doesn't work at all, I logged out of my account, QR login is available (which I believe the injection disables) and when I type my pass + 2fa code and login, there's no embed sent by the webhook with the password and other account data like it used to do before. Other than that great work, appreciate it, I wanted to say that your grabber along with your RAT helped me take revenge from a guy who stole my work and sold it and took the money to himself, so token grabbers aren't always a bad thing.

lmao no worries, ill look into the injection and why it isnt working. Discord recently did a update so thats probably why

**Comment by NerosKing** [comment]
Yo, i used it for a long time and it worked perfectly fine. But now when people run it litteraly nothing happends. It doesn't close discord or send any info to the webhook. I used a binder to bind it with another program and the other one works. So it needs to be something wrong with the grabber itself. Thanks!

**Comment by Rdimo** [comment]
> Yo, i used it for a long time and it worked perfectly fine. But now when people run it litteraly nothing happends. It doesn't close discord or send any info to the webhook. I used a binder to bind it with another program and the other one works. So it needs to be something wrong with the grabber itself. Thanks!

yes that issue is fixed, the reason it wasn't working was because of discord updating their module_core, added in the new version now so whenever discord updates it again, hazard will be able to find it no matter what version. If that makes sense

**Comment by Rdimo** [comment]
so just redownload and run it like normal and it should work just fine. Otherwise please tell me if ur getting some sort of error

**Comment by NerosKing** [comment]
So I need to download Hazard Nuker again?

**Comment by NerosKing** [comment]
https://user-images.githubusercontent.com/94551215/173367823-fcb9a10f-8c4d-4eb0-977a-50232a19212e.mp4

Still doesn't work. It opends some cmd tabs real quick and closes them. Here is a vid

**Comment by Rdimo** [comment]
> 2022-06-13_15-46-04.mp4 
> Still doesn't work. It opends some cmd tabs real quick and closes them. Here is a vid

ah, you know it has anti-vm right?

**Comment by Rdimo** [comment]
haven't found an issue with injection so closing this issue
